import models
from database import SessionLocal, engine

def import_video_games():
    models.Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    
    # Base tag
    root_tag = db.query(models.Tag).filter(models.Tag.name == "jeu-vidéo").first()
    if not root_tag:
        root_tag = models.Tag(name="jeu-vidéo")
        db.add(root_tag)
        db.commit()
        db.refresh(root_tag)

    # Data structure (n: name, y: year, t: sub-tags)
    hardware = [
        {"n":"Magnavox Odyssey","y":1972,"t":["console","1ère gén"]},
        {"n":"Atari 2600","y":1977,"t":["console","atari","2ème gén"]},
        {"n":"ColecoVision","y":1982,"t":["console","2ème gén"]},
        {"n":"Nintendo Entertainment System (NES)","y":1983,"t":["console","nintendo","8-bit"]},
        {"n":"Commodore 64","y":1982,"t":["ordinateur","commodore"]},
        {"n":"Apple II","y":1977,"t":["ordinateur","apple"]},
        {"n":"ZX Spectrum","y":1982,"t":["ordinateur","sinclair"]},
        {"n":"Amstrad CPC 464","y":1984,"t":["ordinateur","amstrad"]},
        {"n":"Sega Master System","y":1985,"t":["console","sega","8-bit"]},
        {"n":"Game Boy","y":1989,"t":["console portable","nintendo"]},
        {"n":"Atari ST","y":1985,"t":["ordinateur","atari"]},
        {"n":"Amiga 500","y":1987,"t":["ordinateur","commodore"]},
        {"n":"Sega Genesis / Mega Drive","y":1988,"t":["console","sega","16-bit"]},
        {"n":"Super Nintendo (SNES)","y":1990,"t":["console","nintendo","16-bit"]},
        {"n":"Neo Geo AES","y":1990,"t":["console","snk"]},
        {"n":"Game Gear","y":1990,"t":["console portable","sega"]},
        {"n":"PlayStation (PS1)","y":1994,"t":["console","sony","32-bit"]},
        {"n":"Sega Saturn","y":1994,"t":["console","sega","32-bit"]},
        {"n":"Nintendo 64","y":1996,"t":["console","nintendo","64-bit"]},
        {"n":"Dreamcast","y":1998,"t":["console","sega"]},
        {"n":"PlayStation 2 (PS2)","y":2000,"t":["console","sony"]},
        {"n":"GameCube","y":2001,"t":["console","nintendo"]},
        {"n":"Xbox","y":2001,"t":["console","microsoft"]},
        {"n":"Game Boy Advance","y":2001,"t":["console portable","nintendo"]},
        {"n":"Nintendo DS","y":2004,"t":["console portable","nintendo"]},
        {"n":"PlayStation Portable (PSP)","y":2004,"t":["console portable","sony"]},
        {"n":"Xbox 360","y":2005,"t":["console","microsoft"]},
        {"n":"PlayStation 3 (PS3)","y":2006,"t":["console","sony"]},
        {"n":"Wii","y":2006,"t":["console","nintendo"]},
        {"n":"Nintendo 3DS","y":2011,"t":["console portable","nintendo"]},
        {"n":"PlayStation Vita","y":2011,"t":["console portable","sony"]},
        {"n":"Wii U","y":2012,"t":["console","nintendo"]},
        {"n":"PlayStation 4 (PS4)","y":2013,"t":["console","sony"]},
        {"n":"Xbox One","y":2013,"t":["console","microsoft"]},
        {"n":"Nintendo Switch","y":2017,"t":["console","nintendo","portable"]},
        {"n":"PlayStation 5 (PS5)","y":2020,"t":["console","sony"]},
        {"n":"Xbox Series X/S","y":2020,"t":["console","microsoft"]},
        {"n":"Steam Deck","y":2022,"t":["console portable","pc"]},
        {"n":"PC Engine / TurboGrafx-16","y":1987,"t":["console","nec"]},
        {"n":"3DO Interactive Multiplayer","y":1993,"t":["console","panasonic"]},
        {"n":"Atari Jaguar","y":1993,"t":["console","atari"]},
        {"n":"Virtual Boy","y":1995,"t":["console","nintendo"]},
        {"n":"Neo Geo Pocket Color","y":1999,"t":["console portable","snk"]},
        {"n":"WonderSwan","y":1999,"t":["console portable","bandai"]},
        {"n":"Ouya","y":2013,"t":["console","android"]}
    ]

    sony = [
        {"n":"Gran Turismo","y":1997,"t":["sony","course"]},
        {"n":"God of War","y":2005,"t":["sony","action"]},
        {"n":"Uncharted: Drake's Fortune","y":2007,"t":["sony","aventure"]},
        {"n":"The Last of Us","y":2013,"t":["sony","survie"]},
        {"n":"Ratchet & Clank","y":2002,"t":["sony","plateforme"]},
        {"n":"Jak and Daxter: The Precursor Legacy","y":2001,"t":["sony","plateforme"]},
        {"n":"Sly Cooper and the Thievius Raccoonus","y":2002,"t":["sony","infiltration"]},
        {"n":"Horizon Zero Dawn","y":2017,"t":["sony","action-rpg"]},
        {"n":"Bloodborne","y":2015,"t":["sony","action-rpg"]},
        {"n":"Demon's Souls","y":2009,"t":["sony","action-rpg"]},
        {"n":"Marvel's Spider-Man","y":2018,"t":["sony","action"]},
        {"n":"Ghost of Tsushima","y":2020,"t":["sony","action"]},
        {"n":"Infamous","y":2009,"t":["sony","action"]},
        {"n":"Resistance: Fall of Man","y":2006,"t":["sony","fps"]},
        {"n":"Killzone 2","y":2009,"t":["sony","fps"]},
        {"n":"LittleBigPlanet","y":2008,"t":["sony","plateforme"]},
        {"n":"Gravity Rush","y":2012,"t":["sony","aventure"]},
        {"n":"MediEvil","y":1998,"t":["sony","action"]},
        {"n":"Ape Escape","y":1999,"t":["sony","plateforme"]},
        {"n":"Syphon Filter","y":1999,"t":["sony","infiltration"]},
        {"n":"Twisted Metal","y":1995,"t":["sony","combat véhiculaire"]},
        {"n":"Wipeout","y":1995,"t":["sony","course"]},
        {"n":"Parappa the Rapper","y":1996,"t":["sony","rythme"]},
        {"n":"Knack","y":2013,"t":["sony","plateforme"]},
        {"n":"Days Gone","y":2019,"t":["sony","survie"]},
        {"n":"Returnal","y":2021,"t":["sony","roguelike"]},
        {"n":"The Last Guardian","y":2016,"t":["sony","aventure"]},
        {"n":"Ico","y":2001,"t":["sony","aventure"]},
        {"n":"Shadow of the Colossus","y":2005,"t":["sony","aventure"]},
        {"n":"Detroit: Become Human","y":2018,"t":["sony","aventure narrative"]},
        {"n":"Heavy Rain","y":2010,"t":["sony","aventure narrative"]},
        {"n":"Until Dawn","y":2015,"t":["sony","horreur"]},
        {"n":"Tearaway","y":2013,"t":["sony","plateforme"]},
        {"n":"Resogun","y":2013,"t":["sony","arcade"]},
        {"n":"Helldivers 2","y":2024,"t":["sony","tir"]},
        {"n":"Journey","y":2012,"t":["sony","indie"]},
        {"n":"Ghosthunter","y":2003,"t":["sony","action"]},
        {"n":"The Getaway","y":2002,"t":["sony","action"]},
        {"n":"MotorStorm","y":2006,"t":["sony","course"]},
        {"n":"Primal","y":2003,"t":["sony","action"]}
    ]

    nintendo = [
        {"n":"Super Mario Bros.","y":1985,"t":["nintendo","plateforme"]},
        {"n":"The Legend of Zelda","y":1986,"t":["nintendo","aventure"]},
        {"n":"Metroid","y":1986,"t":["nintendo","action-aventure"]},
        {"n":"Donkey Kong","y":1981,"t":["nintendo","arcade"]},
        {"n":"Kirby's Dream Land","y":1992,"t":["nintendo","plateforme"]},
        {"n":"Star Fox","y":1993,"t":["nintendo","shoot 'em up"]},
        {"n":"Pokémon Version Rouge / Bleue","y":1996,"t":["nintendo","rpg"]},
        {"n":"F-Zero","y":1990,"t":["nintendo","course"]},
        {"n":"EarthBound","y":1994,"t":["nintendo","rpg"]},
        {"n":"Fire Emblem: Shadow Dragon","y":1990,"t":["nintendo","stratégie"]},
        {"n":"Animal Crossing","y":2001,"t":["nintendo","simulation"]},
        {"n":"Pikmin","y":2001,"t":["nintendo","stratégie"]},
        {"n":"Splatoon","y":2015,"t":["nintendo","tir"]},
        {"n":"Xenoblade Chronicles","y":2010,"t":["nintendo","rpg"]},
        {"n":"Super Smash Bros.","y":1999,"t":["nintendo","combat"]},
        {"n":"Mario Kart 64","y":1996,"t":["nintendo","course"]},
        {"n":"Luigi's Mansion","y":2001,"t":["nintendo","aventure"]},
        {"n":"WarioWare, Inc.","y":2003,"t":["nintendo","party game"]},
        {"n":"Punch-Out!!","y":1987,"t":["nintendo","sport"]},
        {"n":"Kid Icarus","y":1986,"t":["nintendo","plateforme"]},
        {"n":"Dr. Mario","y":1990,"t":["nintendo","puzzle"]},
        {"n":"Super Mario World 2: Yoshi's Island","y":1995,"t":["nintendo","plateforme"]},
        {"n":"Paper Mario","y":2000,"t":["nintendo","rpg"]},
        {"n":"Mario Party","y":1998,"t":["nintendo","party game"]},
        {"n":"Wii Sports","y":2006,"t":["nintendo","sport"]},
        {"n":"Nintendogs","y":2005,"t":["nintendo","simulation"]},
        {"n":"Brain Age","y":2005,"t":["nintendo","puzzle"]},
        {"n":"Golden Sun","y":2001,"t":["nintendo","rpg"]},
        {"n":"Advance Wars","y":2001,"t":["nintendo","stratégie"]},
        {"n":"Excitebike","y":1984,"t":["nintendo","course"]},
        {"n":"Ice Climber","y":1985,"t":["nintendo","plateforme"]},
        {"n":"Balloon Fight","y":1984,"t":["nintendo","arcade"]},
        {"n":"Duck Hunt","y":1984,"t":["nintendo","arcade"]},
        {"n":"Game & Watch: Ball","y":1980,"t":["nintendo","arcade"]},
        {"n":"Bayonetta 2","y":2014,"t":["nintendo","action"]},
        {"n":"Astral Chain","y":2019,"t":["nintendo","action"]},
        {"n":"ARMS","y":2017,"t":["nintendo","combat"]},
        {"n":"Ring Fit Adventure","y":2019,"t":["nintendo","sport"]},
        {"n":"Tetris (Game Boy)","y":1989,"t":["nintendo","puzzle"]},
        {"n":"Mario Paint","y":1992,"t":["nintendo","créativité"]}
    ]

    microsoft = [
        {"n":"Halo: Combat Evolved","y":2001,"t":["microsoft","fps"]},
        {"n":"Gears of War","y":2006,"t":["microsoft","tir"]},
        {"n":"Forza Motorsport","y":2005,"t":["microsoft","course"]},
        {"n":"Forza Horizon","y":2012,"t":["microsoft","course"]},
        {"n":"Fable","y":2004,"t":["microsoft","rpg"]},
        {"n":"Sea of Thieves","y":2018,"t":["microsoft","aventure"]},
        {"n":"State of Decay","y":2013,"t":["microsoft","survie"]},
        {"n":"Ori and the Blind Forest","y":2015,"t":["microsoft","plateforme","indie"]},
        {"n":"Cuphead","y":2017,"t":["microsoft","action","indie"]},
        {"n":"Psychonauts 2","y":2021,"t":["microsoft","plateforme"]},
        {"n":"Sunset Overdrive","y":2014,"t":["microsoft","action"]},
        {"n":"Quantum Break","y":2016,"t":["microsoft","action"]},
        {"n":"Alan Wake","y":2010,"t":["microsoft","aventure"]},
        {"n":"Crackdown","y":2007,"t":["microsoft","action"]},
        {"n":"Gears Tactics","y":2020,"t":["microsoft","stratégie"]},
        {"n":"Battletoads (2020)","y":2020,"t":["microsoft","beat 'em up"]},
        {"n":"Killer Instinct (2013)","y":2013,"t":["microsoft","combat"]},
        {"n":"ReCore","y":2016,"t":["microsoft","aventure"]},
        {"n":"Viva Piñata","y":2006,"t":["microsoft","simulation"]},
        {"n":"Project Gotham Racing","y":2001,"t":["microsoft","course"]},
        {"n":"Blinx: The Time Sweeper","y":2002,"t":["microsoft","plateforme"]},
        {"n":"Voodoo Vince","y":2003,"t":["microsoft","plateforme"]},
        {"n":"Phantom Dust","y":2004,"t":["microsoft","stratégie"]},
        {"n":"Gears 5","y":2019,"t":["microsoft","tir"]},
        {"n":"Halo Infinite","y":2021,"t":["microsoft","fps"]},
        {"n":"Microsoft Flight Simulator (2020)","y":2020,"t":["microsoft","simulation"]},
        {"n":"Age of Empires IV","y":2021,"t":["microsoft","stratégie"]},
        {"n":"Pentiment","y":2022,"t":["microsoft","aventure narrative"]},
        {"n":"Hi-Fi Rush","y":2023,"t":["microsoft","rythme"]},
        {"n":"Grounded","y":2020,"t":["microsoft","survie"]},
        {"n":"Blue Dragon","y":2006,"t":["microsoft","rpg"]},
        {"n":"Lost Odyssey","y":2007,"t":["microsoft","rpg"]},
        {"n":"Mass Effect (Xbox 360)","y":2007,"t":["microsoft","rpg"]},
        {"n":"Ryse: Son of Rome","y":2013,"t":["microsoft","action"]},
        {"n":"Dead Rising","y":2006,"t":["microsoft","action"]},
        {"n":"Banjo-Kazooie: Nuts & Bolts","y":2008,"t":["microsoft","aventure"]},
        {"n":"Perfect Dark Zero","y":2005,"t":["microsoft","fps"]},
        {"n":"Jade Empire","y":2005,"t":["microsoft","rpg"]},
        {"n":"Avowed","y":2024,"t":["microsoft","rpg"]},
        {"n":"Starfield","y":2023,"t":["microsoft","rpg"]}
    ]

    pc_games = [
        {"n":"Half-Life","y":1998,"t":["pc","valve","fps"]},
        {"n":"Doom","y":1993,"t":["pc","id","fps"]},
        {"n":"Quake","y":1996,"t":["pc","id","fps"]},
        {"n":"StarCraft","y":1998,"t":["pc","blizzard","stratégie"]},
        {"n":"Warcraft: Orcs & Humans","y":1994,"t":["pc","blizzard","stratégie"]},
        {"n":"Diablo","y":1996,"t":["pc","blizzard","action-rpg"]},
        {"n":"World of Warcraft","y":2004,"t":["pc","blizzard","mmorpg"]},
        {"n":"Counter-Strike","y":2000,"t":["pc","valve","fps"]},
        {"n":"Dota 2","y":2013,"t":["pc","valve","moba"]},
        {"n":"League of Legends","y":2009,"t":["pc","riot","moba"]},
        {"n":"Minecraft","y":2011,"t":["pc","bac à sable"]},
        {"n":"The Sims","y":2000,"t":["pc","simulation"]},
        {"n":"Civilization","y":1991,"t":["pc","stratégie"]},
        {"n":"SimCity","y":1989,"t":["pc","stratégie"]},
        {"n":"Age of Empires","y":1997,"t":["pc","stratégie"]},
        {"n":"Command & Conquer","y":1995,"t":["pc","stratégie"]},
        {"n":"Baldur's Gate","y":1998,"t":["pc","rpg"]},
        {"n":"Fallout","y":1997,"t":["pc","rpg"]},
        {"n":"The Elder Scrolls: Arena","y":1994,"t":["pc","rpg"]},
        {"n":"The Secret of Monkey Island","y":1990,"t":["pc","aventure"]},
        {"n":"Day of the Tentacle","y":1993,"t":["pc","aventure"]},
        {"n":"Grim Fandango","y":1998,"t":["pc","aventure"]},
        {"n":"Myst","y":1993,"t":["pc","aventure"]},
        {"n":"Deus Ex","y":2000,"t":["pc","rpg","fps"]},
        {"n":"Thief: The Dark Project","y":1998,"t":["pc","infiltration"]},
        {"n":"System Shock","y":1994,"t":["pc","action-rpg"]},
        {"n":"BioShock","y":2007,"t":["pc","fps"]},
        {"n":"Crysis","y":2007,"t":["pc","fps"]},
        {"n":"Portal","y":2007,"t":["pc","valve","puzzle"]},
        {"n":"Team Fortress 2","y":2007,"t":["pc","valve","fps"]},
        {"n":"Undertale","y":2015,"t":["pc","indie","rpg"]},
        {"n":"Stardew Valley","y":2016,"t":["pc","indie","simulation"]},
        {"n":"Terraria","y":2011,"t":["pc","indie","bac à sable"]},
        {"n":"The Binding of Isaac","y":2011,"t":["pc","indie","roguelike"]},
        {"n":"Spelunky","y":2008,"t":["pc","indie","roguelike"]},
        {"n":"Papers, Please","y":2013,"t":["pc","indie","simulation"]},
        {"n":"Factorio","y":2020,"t":["pc","indie","stratégie"]},
        {"n":"RimWorld","y":2018,"t":["pc","indie","stratégie"]},
        {"n":"Kerbal Space Program","y":2015,"t":["pc","indie","simulation"]},
        {"n":"Disco Elysium","y":2019,"t":["pc","indie","rpg"]},
        {"n":"Outer Wilds","y":2019,"t":["pc","indie","aventure"]},
        {"n":"Hades","y":2020,"t":["pc","indie","roguelike"]},
        {"n":"Hollow Knight","y":2017,"t":["pc","indie","metroidvania"]},
        {"n":"Celeste","y":2018,"t":["pc","indie","plateforme"]},
        {"n":"Slay the Spire","y":2019,"t":["pc","indie","stratégie"]},
        {"n":"Vampire Survivors","y":2022,"t":["pc","indie","action"]},
        {"n":"Valheim","y":2021,"t":["pc","indie","survie"]},
        {"n":"Phasmophobia","y":2020,"t":["pc","indie","horreur"]},
        {"n":"Among Us","y":2018,"t":["pc","indie"]},
        {"n":"Rust","y":2018,"t":["pc","survie"]},
        {"n":"DayZ","y":2018,"t":["pc","survie"]},
        {"n":"Garry's Mod","y":2006,"t":["pc","bac à sable"]},
        {"n":"Second Life","y":2003,"t":["pc","mmo"]},
        {"n":"EVE Online","y":2003,"t":["pc","mmorpg"]},
        {"n":"Guild Wars","y":2005,"t":["pc","mmorpg"]},
        {"n":"EverQuest","y":1999,"t":["pc","mmorpg"]},
        {"n":"Ultima Online","y":1997,"t":["pc","mmorpg"]},
        {"n":"The Oregon Trail","y":1971,"t":["pc","historique"]},
        {"n":"Lemmings","y":1991,"t":["pc","puzzle"]},
        {"n":"Worms","y":1995,"t":["pc","stratégie"]},
        {"n":"RollerCoaster Tycoon","y":1999,"t":["pc","simulation"]},
        {"n":"Theme Hospital","y":1997,"t":["pc","simulation"]},
        {"n":"Dungeon Keeper","y":1997,"t":["pc","stratégie"]},
        {"n":"Black & White","y":2001,"t":["pc","simulation"]},
        {"n":"Populous","y":1989,"t":["pc","stratégie"]},
        {"n":"King's Quest","y":1984,"t":["pc","aventure"]},
        {"n":"Space Quest","y":1986,"t":["pc","aventure"]},
        {"n":"Police Quest","y":1987,"t":["pc","aventure"]},
        {"n":"Leisure Suit Larry in the Land of the Lounge Lizards","y":1987,"t":["pc","aventure"]},
        {"n":"Zork I","y":1980,"t":["pc","aventure textuelle"]},
        {"n":"Colossal Cave Adventure","y":1976,"t":["pc","aventure textuelle"]},
        {"n":"Elite","y":1984,"t":["pc","simulation"]},
        {"n":"Rogue","y":1980,"t":["pc","roguelike"]},
        {"n":"Dwarf Fortress","y":2006,"t":["pc","simulation"]},
        {"n":"Vampire: The Masquerade – Bloodlines","y":2004,"t":["pc","rpg"]},
        {"n":"Planescape: Torment","y":1999,"t":["pc","rpg"]},
        {"n":"Icewind Dale","y":2000,"t":["pc","rpg"]},
        {"n":"Neverwinter Nights","y":2002,"t":["pc","rpg"]},
        {"n":"Star Wars: Knights of the Old Republic","y":2003,"t":["pc","rpg"]},
        {"n":"The Witcher","y":2007,"t":["pc","rpg"]},
        {"n":"Cyberpunk 2077","y":2020,"t":["pc","rpg"]},
        {"n":"Solitaire (Windows)","y":1990,"t":["pc","puzzle"]},
        {"n":"Démineur (Minesweeper)","y":1990,"t":["pc","puzzle"]},
        {"n":"Flight Simulator 1.0","y":1982,"t":["pc","simulation"]},
        {"n":"Wolfenstein 3D","y":1992,"t":["pc","id","fps"]},
        {"n":"Duke Nukem 3D","y":1996,"t":["pc","fps"]},
        {"n":"Unreal Tournament","y":1999,"t":["pc","fps"]},
        {"n":"Max Payne","y":2001,"t":["pc","action"]},
        {"n":"Left 4 Dead","y":2008,"t":["pc","fps"]},
        {"n":"Total War: Shogun","y":2000,"t":["pc","stratégie"]},
        {"n":"Homeworld","y":1999,"t":["pc","stratégie"]},
        {"n":"Company of Heroes","y":2006,"t":["pc","stratégie"]},
        {"n":"Star Wars: TIE Fighter","y":1994,"t":["pc","simulation"]},
        {"n":"MechWarrior 2","y":1995,"t":["pc","simulation"]},
        {"n":"Crysis Warhead","y":2008,"t":["pc","fps"]},
        {"n":"S.T.A.L.K.E.R.: Shadow of Chernobyl","y":2007,"t":["pc","fps"]},
        {"n":"Mount & Blade","y":2008,"t":["pc","rpg"]},
        {"n":"Amnesia: The Dark Descent","y":2010,"t":["pc","horreur"]},
        {"n":"Cities: Skylines","y":2015,"t":["pc","stratégie"]},
        {"n":"Baldur's Gate 3","y":2023,"t":["pc","rpg"]}
    ]

    others = [
        {"n":"Pac-Man","y":1980,"t":["arcade","namco"]},
        {"n":"Space Invaders","y":1978,"t":["arcade","taito"]},
        {"n":"Asteroids","y":1979,"t":["arcade","atari"]},
        {"n":"Galaga","y":1981,"t":["arcade","namco"]},
        {"n":"Centipede","y":1981,"t":["arcade","atari"]},
        {"n":"Pitfall!","y":1982,"t":["atari","plateforme"]},
        {"n":"Frogger","y":1981,"t":["arcade","konami"]},
        {"n":"Street Fighter II","y":1991,"t":["arcade","capcom","combat"]},
        {"n":"Mortal Kombat","y":1992,"t":["arcade","midway","combat"]},
        {"n":"Sonic the Hedgehog","y":1991,"t":["sega","plateforme"]},
        {"n":"Resident Evil","y":1996,"t":["capcom","horreur"]},
        {"n":"Silent Hill","y":1999,"t":["konami","horreur"]},
        {"n":"Metal Gear Solid","y":1998,"t":["konami","infiltration"]},
        {"n":"Final Fantasy","y":1987,"t":["square","rpg"]},
        {"n":"Castlevania","y":1986,"t":["konami","plateforme"]},
        {"n":"Mega Man","y":1987,"t":["capcom","plateforme"]},
        {"n":"Contra","y":1987,"t":["konami","action"]},
        {"n":"Double Dragon","y":1987,"t":["arcade","beat 'em up"]},
        {"n":"Golden Axe","y":1989,"t":["sega","beat 'em up"]},
        {"n":"Shinobi","y":1987,"t":["sega","action"]},
        {"n":"Streets of Rage","y":1991,"t":["sega","beat 'em up"]},
        {"n":"Phantasy Star","y":1987,"t":["sega","rpg"]},
        {"n":"Virtua Fighter","y":1993,"t":["sega","combat"]},
        {"n":"Tekken","y":1994,"t":["namco","combat"]},
        {"n":"SoulCalibur","y":1998,"t":["namco","combat"]},
        {"n":"Tomb Raider","y":1996,"t":["aventure"]},
        {"n":"Rayman","y":1995,"t":["plateforme"]},
        {"n":"Crash Bandicoot","y":1996,"t":["sony","plateforme"]},
        {"n":"Spyro the Dragon","y":1998,"t":["sony","plateforme"]},
        {"n":"Prince of Persia","y":1989,"t":["plateforme"]},
        {"n":"Pong","y":1972,"t":["arcade","atari"]},
        {"n":"Breakout","y":1976,"t":["arcade","atari"]},
        {"n":"Dragon's Lair","y":1983,"t":["arcade","aventure"]},
        {"n":"Bubble Bobble","y":1986,"t":["arcade","taito"]},
        {"n":"Arkanoid","y":1986,"t":["arcade","taito"]},
        {"n":"R-Type","y":1987,"t":["arcade","irem"]},
        {"n":"Gradius","y":1985,"t":["arcade","konami"]},
        {"n":"Tetris (Original)","y":1984,"t":["puzzle","urss"]},
        {"n":"Bomberman","y":1983,"t":["hudson soft","action"]},
        {"n":"Out Run","y":1986,"t":["sega","course"]},
        {"n":"Metal Slug","y":1996,"t":["snk","action"]},
        {"n":"The King of Fighters '94","y":1994,"t":["snk","combat"]},
        {"n":"Samurai Shodown","y":1993,"t":["snk","combat"]},
        {"n":"Pac-Man Championship Edition","y":2007,"t":["namco","arcade"]},
        {"n":"Space Harrier","y":1985,"t":["sega","shoot 'em up"]},
        {"n":"Daytona USA","y":1993,"t":["sega","course"]},
        {"n":"Crazy Taxi","y":1999,"t":["sega","course"]},
        {"n":"Shenmue","y":1999,"t":["sega","aventure"]},
        {"n":"Sonic Adventure","y":1998,"t":["sega","plateforme"]},
        {"n":"Nights into Dreams","y":1996,"t":["sega","action"]},
        {"n":"Jet Set Radio","y":2000,"t":["sega","action"]},
        {"n":"Alex Kidd in Miracle World","y":1986,"t":["sega","plateforme"]},
        {"n":"Panzer Dragoon","y":1995,"t":["sega","action"]},
        {"n":"Wonder Boy","y":1986,"t":["sega","plateforme"]},
        {"n":"Shining Force","y":1992,"t":["sega","rpg"]},
        {"n":"Vectrex","y":1982,"t":["console"]},
        {"n":"Intellivision","y":1979,"t":["console","mattel"]},
        {"n":"Atari 5200","y":1982,"t":["console","atari"]},
        {"n":"Atari 7800","y":1986,"t":["console","atari"]},
        {"n":"Lynx","y":1989,"t":["console portable","atari"]},
        {"n":"Atari XEGS","y":1987,"t":["console","atari"]},
        {"n":"Ghouls 'n Ghosts","y":1988,"t":["capcom","action"]},
        {"n":"Final Fight","y":1989,"t":["capcom","beat 'em up"]},
        {"n":"Captain Commando","y":1991,"t":["capcom","beat 'em up"]},
        {"n":"Strider","y":1989,"t":["capcom","action"]},
        {"n":"Darkstalkers","y":1994,"t":["capcom","combat"]},
        {"n":"Dino Crisis","y":1999,"t":["capcom","horreur"]},
        {"n":"Okami","y":2006,"t":["capcom","aventure"]},
        {"n":"Devil May Cry","y":2001,"t":["capcom","action"]},
        {"n":"Monster Hunter","y":2004,"t":["capcom","action-rpg"]},
        {"n":"Phoenix Wright: Ace Attorney","y":2001,"t":["capcom","aventure"]},
        {"n":"Deadly Premonition","y":2010,"t":["horreur"]},
        {"n":"Shenmue II","y":2001,"t":["sega","aventure"]},
        {"n":"Yakuza","y":2005,"t":["sega","action"]},
        {"n":"Skies of Arcadia","y":2000,"t":["sega","rpg"]},
        {"n":"Valkyria Chronicles","y":2008,"t":["sega","stratégie"]},
        {"n":"Bayonetta","y":2009,"t":["sega","action"]},
        {"n":"Vanquish","y":2010,"t":["sega","action"]},
        {"n":"Persona 5","y":2016,"t":["atlus","rpg"]},
        {"n":"Shin Megami Tensei III: Nocturne","y":2003,"t":["atlus","rpg"]}
    ]

    all_data = hardware + sony + nintendo + microsoft + pc_games + others
    
    count = 0
    for d in all_data:
        # Get/Create tags
        db_tags = [root_tag]
        for t_name in d["t"]:
            tag = db.query(models.Tag).filter(models.Tag.name == t_name).first()
            if not tag:
                tag = models.Tag(name=t_name)
                db.add(tag)
                db.commit()
                db.refresh(tag)
            db_tags.append(tag)
            
        card = models.Card(
            name=d["n"],
            image_url=None,
            wiki_link=f"https://fr.wikipedia.org/wiki/{d['n'].replace(' ', '_')}",
            attributes={
                "année": d["y"]
            },
            tags=db_tags
        )
        db.add(card)
        count += 1
        if count % 50 == 0:
            db.commit()
            print(f"Importation: {count} fiches...")

    db.commit()
    db.close()
    print(f"Bdd mise à jour avec {count} nouvelles fiches jeu-vidéo!")

if __name__ == "__main__":
    import_video_games()
